### ISSUE TITLE
Type encode error in scala/http

### ISSUE THREAD

**Issue by bjmiller** [specgen-io/specgen#136]
@vsapronov:
Looking at this:
https://github.com/specgen-io/specgen/blob/dee88d71df85af66596c8a44e80720b8e81a704d/gen/scala/http.go#L47

```
def decode(s: String): Long = s.toShort
```

I think that this should be `s.toLong`?  If I'm right, then this is actually causing a bug in a generated service.

**Comment by JennyLeahy** [comment]
Just to be clear: the consequence is for numbers greater than 32767 (the upper most of short data type in Java), we get a decode error. 

@vsapronov This is important to us. Thanks for the help.

**Comment by vsapronov** [comment]
This is certainly a bug. Thank you for reporting.
I will let you know as soon as the build with the fix will be available (should be this week).

**Comment by vsapronov** [comment]
Created work item: https://trello.com/c/u7e6BVxy/198-fix-scala-long-types-bug

**Comment by vsapronov** [comment]
@JennyLeahy Could you please try version `2.1.1828` of the `sbt-specgen` plugin. I would recommend to try it just one service to see if it creates any backward incompatibilities.
